spring:
  kafka:
    bootstrap-servers: 120.46.194.37:9092
    producer: # 生产者
      retries: 3 # 设置大于0的值，则客户端会将发送失败的记录重新发送
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: common.log.scholar_of_yore.serializer.CommonValueSerializer
    template:
      default-topic: common.log.scholar-of-yore.common-log
common:
  log:
    scholar-of-yore: 127.0.0.1:8889